version: '3.8'

services:
  api:
    image: corona_api
    build:
      dockerfile: ./Dockerfile.local
    tty: true
    ports:
      - "8001:8001"
    volumes:
      - .:/usr/src/app
  mysql:
    image: mysql:8.0
    container_name: localDB
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'corona'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 23306:3306


