info:
  contact: {}
paths:
  /patients/details/:
    get:
      consumes:
      - application/json
      description: 指定した期間と都道府県の感染者数情報を取得する
      parameters:
      - description: 開始日
        example: 20230101
        in: query
        name: start_date
        type: integer
      - description: 終了日
        example: 20230102
        in: query
        name: end_date
        type: integer
      - description: 都道府県名
        example: '"北海道"'
        in: query
        name: area
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: 感染者数詳細リスト取得
      tags:
      - Patients
swagger: "2.0"
