host: localhost:8081
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /patient/details/:
    get:
      consumes:
      - application/json
      description: 2020/05/09から前日までの指定都道府県の感染者数情報を取得する
      parameters:
      - description: 開始日
        example: 20230101
        in: query
        name: start_date
        type: integer
      - description: 終了日
        example: 20230102
        in: query
        name: end_date
        type: integer
      - description: 都道府県名
        example: '"北海道"'
        in: query
        name: area
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: 感染者数詳細リスト取得
      tags:
      - Patients
swagger: "2.0"
